name: Test generated MIPS Code

on: [push]

jobs:
  test:
    name: Run MIPS tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Spim (MIPS simulator)
        run: sudo apt install -y spim
      - name: Run all tests
        run: |
          pytest src/tests/MIPS_tests -n auto
